<?php
if($this->isEnabled()){
    ?>
    <script src="https://dash.unbeatable.com/public/widget.js?client=<?php echo $this->getApiKey(); ?>" async></script>
    <script>
         function ajax(url, callback, data, x) {
            try {
                x = new(this.XMLHttpRequest || ActiveXObject)('MSXML2.XMLHTTP.3.0');
                x.open(data ? 'POST' : 'GET', url, 1);
                x.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                x.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
                x.onreadystatechange = function () {
                    x.readyState > 3 && callback && callback(x.responseText, x);
                };
                x.send(data)
            } catch (e) {
                window.console && console.log(e);
            }
        };
        function UnbeatableReady() {
            ajax('<?php echo Mage::getBaseUrl(); ?>unbeatable/cart/index', function(response){
                Unbeatable.setItems(JSON.parse(response));
            });
        }
        </script>
<?php
}
?>
